"""Render a StudyPlan into clean Markdown for download."""
from __future__ import annotations

from app.schemas import StudyPlan


def render_markdown(plan: StudyPlan) -> str:
    req = plan.request
    out: list[str] = []
    a = out.append

    a(f"# {plan.outline.title}")
    a("")
    a(
        f"**Class {req.grade} · {req.subject} · {req.topic}**  "
        f"\n_{req.duration_weeks} week(s) · ~{req.hours_per_week} hrs/week · "
        f"level: {req.level}_"
    )
    a("")
    a(plan.outline.overview)
    a("")

    if plan.outline.learning_goals:
        a("## 🎯 Learning Goals")
        for g in plan.outline.learning_goals:
            a(f"- {g}")
        a("")

    if plan.outline.prerequisites:
        a("## 📋 Prerequisites")
        for p in plan.outline.prerequisites:
            a(f"- {p}")
        a("")

    if plan.curriculum.modules:
        a("## 📚 Curriculum")
        for i, m in enumerate(plan.curriculum.modules, 1):
            a(f"### Module {i}: {m.title}")
            if m.objectives:
                a("**Objectives:**")
                for o in m.objectives:
                    a(f"- {o}")
            if m.subtopics:
                a("**Subtopics:** " + ", ".join(m.subtopics))
            a("")

    if plan.schedule.weeks:
        a("## 🗓️ Schedule")
        for w in plan.schedule.weeks:
            a(f"### Week {w.week_number} — {w.focus}")
            for s in w.sessions:
                a(f"- **{s.day}** ({s.duration_minutes} min): {s.activity}")
            a("")

    if plan.resources.resources:
        a("## 🔗 Resources")
        for r in plan.resources.resources:
            line = f"- **[{r.type}]** {r.title} — {r.description}"
            if r.link:
                line += f" ({r.link})"
            a(line)
        a("")

    if plan.assessment.assessments:
        a("## ✅ Assessments & Checkpoints")
        for asm in plan.assessment.assessments:
            a(f"### {asm.title} ({asm.type})")
            a(asm.description)
            if asm.sample_questions:
                a("**Sample questions:**")
                for q in asm.sample_questions:
                    a(f"- {q}")
            a("")

    q = plan.quiz
    if q.total():
        a("## 📝 Quiz")

        if q.short_questions:
            a("### Short Questions")
            for i, item in enumerate(q.short_questions, 1):
                a(f"{i}. {item.question}")
                a(f"   - **Answer:** {item.answer}")
            a("")

        if q.mcqs:
            a("### Multiple Choice (single answer)")
            for i, item in enumerate(q.mcqs, 1):
                a(f"{i}. {item.question}")
                for j, opt in enumerate(item.options):
                    a(f"   {chr(65 + j)}. {opt}")
                a(f"   - **Answer:** {item.answer}")
            a("")

        if q.multi_select_mcqs:
            a("### Multiple Select (MMCQ — one or more answers)")
            for i, item in enumerate(q.multi_select_mcqs, 1):
                a(f"{i}. {item.question}")
                for j, opt in enumerate(item.options):
                    a(f"   {chr(65 + j)}. {opt}")
                a(f"   - **Answers:** {', '.join(item.answers)}")
            a("")

        if q.fill_in_the_blanks:
            a("### Fill in the Blanks")
            for i, item in enumerate(q.fill_in_the_blanks, 1):
                a(f"{i}. {item.question}")
                a(f"   - **Answer:** {item.answer}")
            a("")

        if q.true_false:
            a("### True / False")
            for i, item in enumerate(q.true_false, 1):
                a(f"{i}. {item.statement}")
                a(f"   - **Answer:** {'True' if item.answer else 'False'}")
            a("")

        if q.case_studies:
            a("### Case-Based Questions")
            for i, case in enumerate(q.case_studies, 1):
                a(f"**Case {i}.** {case.scenario}")
                for j, sq in enumerate(case.questions, 1):
                    a(f"   {i}.{j} {sq.question}")
                    a(f"      - **Answer:** {sq.answer}")
                a("")

        if q.long_questions:
            a("### Long Answer Questions")
            for i, item in enumerate(q.long_questions, 1):
                a(f"{i}. {item.question}")
                a(f"   - **Answer:** {item.answer}")
            a("")

    if plan.study_tips:
        a("## 💡 Study Tips")
        for t in plan.study_tips:
            a(f"- {t}")
        a("")

    a("---")
    a("_Generated by the Multi-Agent Study Planner._")
    return "\n".join(out)
