"""Build a runnable Jupyter EDA notebook (.ipynb) for a generated dataset.

The notebook is emitted as plain ``nbformat`` v4 JSON (no dependency on the
``nbformat`` package). It contains live code cells that load the exported
dataset and render the standard EDA views — shape, dtypes, summary statistics,
missing-value map, target distribution, numeric histograms, a correlation
heatmap, and categorical breakdowns — plus a markdown cell embedding the
precomputed EDA summary so the report is informative even before it is run.

Running the notebook requires ``pandas`` and ``matplotlib`` (both in
``requirements.txt``).
"""

from __future__ import annotations

import itertools
import json
from typing import Any

from app.models.spec import DatasetSpec, DType, FeatureRole

# Deterministic, unique cell ids (required by nbformat >= 4.5).
_cell_counter = itertools.count(1)


def _cell_id() -> str:
    return f"cell-{next(_cell_counter):03d}"


def _md(source: str) -> dict[str, Any]:
    return {
        "cell_type": "markdown",
        "id": _cell_id(),
        "metadata": {},
        "source": source,
    }


def _code(source: str) -> dict[str, Any]:
    return {
        "cell_type": "code",
        "id": _cell_id(),
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source,
    }


def _loader(data_filename: str) -> str:
    """Code that loads the dataset by extension, relative to the notebook."""

    return (
        'from pathlib import Path\n'
        f'DATA_FILE = Path("{data_filename}")\n'
        "if DATA_FILE.suffix == '.parquet':\n"
        "    df = pd.read_parquet(DATA_FILE)\n"
        "elif DATA_FILE.suffix == '.json':\n"
        "    df = pd.read_json(DATA_FILE)\n"
        "else:\n"
        "    df = pd.read_csv(DATA_FILE)\n"
        "print(f'Loaded {len(df):,} rows x {df.shape[1]} columns')\n"
        "df.head()"
    )


def build_eda_notebook(
    spec: DatasetSpec,
    eda: dict[str, Any],
    data_filename: str,
    readiness: float | None = None,
) -> dict[str, Any]:
    """Return the notebook as an nbformat-v4 dict."""

    target = spec.target.name if spec.target else None
    numeric_features = [
        f.name
        for f in spec.features
        if f.dtype in {DType.FLOAT, DType.INTEGER} and f.role == FeatureRole.FEATURE
    ]
    categorical_features = [
        f.name
        for f in spec.features
        if f.dtype in {DType.CATEGORY, DType.ORDINAL}
    ]

    cells: list[dict[str, Any]] = []

    # -- Title & context -------------------------------------------------
    header = [
        f"# EDA Report — {spec.name}",
        "",
        f"- **Domain:** {spec.domain}",
        f"- **Task:** {spec.task_type.value}",
        f"- **Rows:** {eda.get('shape', {}).get('rows', 'n/a'):,}"
        if isinstance(eda.get("shape", {}).get("rows"), int)
        else f"- **Rows:** {eda.get('shape', {}).get('rows', 'n/a')}",
        f"- **Columns:** {eda.get('shape', {}).get('columns', 'n/a')}",
    ]
    if target:
        header.append(f"- **Target:** `{target}`")
    if readiness is not None:
        header.append(f"- **ML readiness score:** {readiness}/100")
    header += [
        "",
        "_Auto-generated by the ML Dataset Generator Agent. "
        "Run all cells to reproduce the analysis._",
    ]
    cells.append(_md("\n".join(header)))

    # -- Precomputed summary (readable without running) ------------------
    cells.append(
        _md(
            "## Precomputed summary\n\n"
            "The pipeline computed the following EDA summary at generation time:\n\n"
            "```json\n" + json.dumps(eda, indent=2, default=str) + "\n```"
        )
    )

    # -- Setup & load ----------------------------------------------------
    cells.append(_md("## Setup"))
    cells.append(
        _code(
            "import pandas as pd\n"
            "import numpy as np\n"
            "import matplotlib.pyplot as plt\n"
            "pd.set_option('display.max_columns', 100)\n"
            "plt.rcParams['figure.figsize'] = (10, 5)"
        )
    )
    cells.append(_md("## Load the dataset"))
    cells.append(_code(_loader(data_filename)))

    # -- Overview --------------------------------------------------------
    cells.append(_md("## Overview: dtypes & structure"))
    cells.append(_code("df.info()"))

    cells.append(_md("## Summary statistics"))
    cells.append(_code("df.describe(include='all').T"))

    # -- Missing values --------------------------------------------------
    cells.append(_md("## Missing values"))
    cells.append(
        _code(
            "missing = df.isna().mean().sort_values(ascending=False)\n"
            "missing = missing[missing > 0]\n"
            "if len(missing):\n"
            "    missing.plot.bar(title='Fraction missing by column')\n"
            "    plt.ylabel('fraction missing'); plt.tight_layout(); plt.show()\n"
            "else:\n"
            "    print('No missing values.')"
        )
    )

    # -- Target distribution ---------------------------------------------
    if target:
        cells.append(_md("## Target distribution"))
        if spec.task_type.is_regression or spec.task_type.value == "time_series":
            cells.append(
                _code(
                    f"df['{target}'].plot.hist(bins=40, "
                    f"title='Distribution of {target}')\n"
                    "plt.tight_layout(); plt.show()"
                )
            )
        else:
            cells.append(
                _code(
                    f"counts = df['{target}'].value_counts()\n"
                    f"counts.plot.bar(title='Class balance — {target}')\n"
                    "plt.ylabel('count'); plt.tight_layout(); plt.show()\n"
                    "counts"
                )
            )

    # -- Numeric histograms ----------------------------------------------
    if numeric_features:
        cells.append(_md("## Numeric feature distributions"))
        cells.append(
            _code(
                f"numeric_features = {numeric_features!r}\n"
                "cols = [c for c in numeric_features if c in df.columns]\n"
                "df[cols].hist(bins=30, figsize=(14, max(3, 3 * ((len(cols)+2)//3))))\n"
                "plt.tight_layout(); plt.show()"
            )
        )

    # -- Correlation heatmap ---------------------------------------------
    cells.append(_md("## Correlation heatmap (numeric features)"))
    cells.append(
        _code(
            "num = df.select_dtypes('number')\n"
            "if num.shape[1] >= 2:\n"
            "    corr = num.corr()\n"
            "    fig, ax = plt.subplots(figsize=(min(14, 1+corr.shape[1]), "
            "min(12, 1+corr.shape[1])))\n"
            "    im = ax.imshow(corr, cmap='coolwarm', vmin=-1, vmax=1)\n"
            "    ax.set_xticks(range(len(corr))); ax.set_xticklabels(corr.columns, "
            "rotation=90)\n"
            "    ax.set_yticks(range(len(corr))); ax.set_yticklabels(corr.columns)\n"
            "    fig.colorbar(im); plt.title('Feature correlations'); "
            "plt.tight_layout(); plt.show()\n"
            "else:\n"
            "    print('Not enough numeric columns for a correlation heatmap.')"
        )
    )

    # -- Categorical breakdowns ------------------------------------------
    if categorical_features:
        cells.append(_md("## Categorical feature breakdowns"))
        cells.append(
            _code(
                f"categorical_features = {categorical_features!r}\n"
                "for col in [c for c in categorical_features if c in df.columns]:\n"
                "    print(f'\\n=== {col} ===')\n"
                "    display(df[col].value_counts(normalize=True).round(4).head(15))"
            )
        )

    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
