"""Command-line interface for the On This Day history agent."""

from __future__ import annotations

import argparse
import datetime as _dt
import sys
from pathlib import Path

from . import __version__
from .agent import DEFAULT_MODEL, ResearchResult, investigate
from .dateparse import DateParseError, ParsedDate, parse_date_input

# Sentinel marking "--pdf given without a path"; resolved to the default later.
_PDF_DEFAULT = "<default>"


def _build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="on-this-day",
        description=(
            "Research what important things happened on a given date. "
            "Provide a full date (e.g. '7 July 1984') for that exact day, or "
            "just a day and month (e.g. '21 July') for a 'this day in history' "
            "overview across all years."
        ),
        epilog="Requires an OpenAI API key in the OPENAI_API_KEY environment variable.",
    )
    parser.add_argument(
        "date",
        nargs="*",
        help="The date to research, e.g. '7 July 1984' or '21 July'.",
    )
    parser.add_argument(
        "-c",
        "--country",
        help="Emphasise events for a particular country (e.g. India).",
    )
    parser.add_argument(
        "-m",
        "--model",
        default=None,
        help=f"OpenAI model to use (default: $OPENAI_MODEL or {DEFAULT_MODEL}).",
    )
    parser.add_argument(
        "-o",
        "--output",
        help="Path to save the Markdown report (default: ./reports/<date>.md).",
    )
    parser.add_argument(
        "--no-save",
        action="store_true",
        help="Do not save the Markdown report to a file.",
    )
    parser.add_argument(
        "--pdf",
        nargs="?",
        const=_PDF_DEFAULT,
        default=None,
        metavar="PATH",
        help=(
            "Also save a sectioned PDF (one section per page). Optionally give a "
            "path; defaults to ./reports/<date>.pdf."
        ),
    )
    parser.add_argument(
        "--no-verify",
        action="store_true",
        help="Skip the independent fact-checking pass (faster, cheaper).",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {__version__}",
    )
    return parser


def _default_output_path(parsed: ParsedDate) -> Path:
    return Path("reports") / f"{parsed.slug()}.md"


def _default_pdf_path(parsed: ParsedDate) -> Path:
    return Path("reports") / f"{parsed.slug()}.pdf"


def _build_document(parsed: ParsedDate, result: ResearchResult, verified: bool) -> str:
    """Wrap the model's Markdown with a small metadata header."""
    generated = _dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    pipeline = "researcher + independent verifier" if verified else "researcher only"
    notes = ""
    if not result.used_web_search:
        notes += "> ⚠️ Web search was unavailable; these results were not web-verified.\n\n"
    elif not verified:
        notes += "> ℹ️ Fact-checking pass was skipped (--no-verify).\n\n"
    header = (
        f"<!-- Generated by on-this-day v{__version__} on {generated} "
        f"using model {result.model} ({pipeline}) -->\n\n"
    )
    return f"{header}{notes}{result.markdown}\n"


def main(argv: list[str] | None = None) -> int:
    args = _build_arg_parser().parse_args(argv)

    date_text = " ".join(args.date).strip()
    if not date_text:
        try:
            date_text = input("Enter a date (e.g. '7 July 1984' or '21 July'): ").strip()
        except (EOFError, KeyboardInterrupt):
            print()
            return 130

    try:
        parsed = parse_date_input(date_text)
    except DateParseError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2

    mode = "exact date" if parsed.has_year else "this day in history"
    print(f"Researching {parsed.human()} ({mode})…", file=sys.stderr)
    if parsed.has_year is False:
        print("Tip: add a year (e.g. '21 July 1969') to research one exact day.",
              file=sys.stderr)

    def report_stage(name: str) -> None:
        if name == "research":
            print("  → Agent 1: searching the web and drafting…", file=sys.stderr)
        elif name == "verify":
            print("  → Agent 2: independently fact-checking the draft…",
                  file=sys.stderr)

    try:
        result = investigate(
            parsed,
            country=args.country,
            model=args.model,
            verify=not args.no_verify,
            on_stage=report_stage,
        )
    except RuntimeError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print("\nCancelled.", file=sys.stderr)
        return 130

    document = _build_document(parsed, result, verified=not args.no_verify)
    print("\n" + document)

    if not args.no_save:
        out_path = Path(args.output) if args.output else _default_output_path(parsed)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(document, encoding="utf-8")
        print(f"Saved report to {out_path}", file=sys.stderr)

    if args.pdf is not None:
        from .pdf import render_markdown_to_pdf  # imported lazily so md-only runs

        pdf_path = (
            _default_pdf_path(parsed)
            if args.pdf == _PDF_DEFAULT
            else Path(args.pdf)
        )
        pdf_path.parent.mkdir(parents=True, exist_ok=True)
        try:
            render_markdown_to_pdf(
                result.markdown, str(pdf_path), title=f"On This Day — {parsed.human()}"
            )
        except RuntimeError as exc:
            print(f"Error: {exc}", file=sys.stderr)
            return 1
        print(f"Saved PDF to {pdf_path}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
