"""Command-line interface for the On This Day history agent."""

from __future__ import annotations

import argparse
import datetime as _dt
import sys
from pathlib import Path

from . import __version__
from .agent import DEFAULT_MODEL, ResearchResult, research_date
from .dateparse import DateParseError, ParsedDate, parse_date_input


def _build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="on-this-day",
        description=(
            "Research what important things happened on a given date. "
            "Provide a full date (e.g. '7 July 1984') for that exact day, or "
            "just a day and month (e.g. '21 July') for a 'this day in history' "
            "overview across all years."
        ),
        epilog="Requires an OpenAI API key in the OPENAI_API_KEY environment variable.",
    )
    parser.add_argument(
        "date",
        nargs="*",
        help="The date to research, e.g. '7 July 1984' or '21 July'.",
    )
    parser.add_argument(
        "-c",
        "--country",
        help="Emphasise events for a particular country (e.g. India).",
    )
    parser.add_argument(
        "-m",
        "--model",
        default=None,
        help=f"OpenAI model to use (default: $OPENAI_MODEL or {DEFAULT_MODEL}).",
    )
    parser.add_argument(
        "-o",
        "--output",
        help="Path to save the Markdown report (default: ./reports/<date>.md).",
    )
    parser.add_argument(
        "--no-save",
        action="store_true",
        help="Print the report but do not save it to a file.",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {__version__}",
    )
    return parser


def _default_output_path(parsed: ParsedDate) -> Path:
    return Path("reports") / f"{parsed.slug()}.md"


def _build_document(parsed: ParsedDate, result: ResearchResult) -> str:
    """Wrap the model's Markdown with a small metadata header."""
    generated = _dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    note = "" if result.used_web_search else (
        "> ⚠️ Web search was unavailable; these results were not web-verified.\n\n"
    )
    header = (
        f"<!-- Generated by on-this-day v{__version__} on {generated} "
        f"using model {result.model} -->\n\n"
    )
    return f"{header}{note}{result.markdown}\n"


def main(argv: list[str] | None = None) -> int:
    args = _build_arg_parser().parse_args(argv)

    date_text = " ".join(args.date).strip()
    if not date_text:
        try:
            date_text = input("Enter a date (e.g. '7 July 1984' or '21 July'): ").strip()
        except (EOFError, KeyboardInterrupt):
            print()
            return 130

    try:
        parsed = parse_date_input(date_text)
    except DateParseError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2

    mode = "exact date" if parsed.has_year else "this day in history"
    print(f"Researching {parsed.human()} ({mode})…", file=sys.stderr)
    if parsed.has_year is False:
        print("Tip: add a year (e.g. '21 July 1969') to research one exact day.",
              file=sys.stderr)

    try:
        result = research_date(parsed, country=args.country, model=args.model)
    except RuntimeError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print("\nCancelled.", file=sys.stderr)
        return 130

    document = _build_document(parsed, result)
    print("\n" + document)

    if not args.no_save:
        out_path = Path(args.output) if args.output else _default_output_path(parsed)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(document, encoding="utf-8")
        print(f"Saved report to {out_path}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
