"""Documentation agent: data dictionary, dataset card, and JSON schema.

Produces human- and machine-readable descriptions of the generated dataset. The
data dictionary is derived from both the spec (intent) and the realised frame
(actual dtypes/stats), so it never drifts from what was produced.
"""

from __future__ import annotations

from typing import Any

import pandas as pd

from app.agents.base import Agent
from app.models.artifacts import GenerationResult
from app.models.spec import DatasetSpec, FeatureRole


class DocumentationAgent(Agent):
    name = "documentation"

    def data_dictionary(self, df: pd.DataFrame, spec: DatasetSpec) -> list[dict]:
        rows = []
        spec_by_name = {f.name: f for f in spec.features}
        for col in df.columns:
            feature = spec_by_name.get(col)
            entry = {
                "column": col,
                "pandas_dtype": str(df[col].dtype),
                "role": feature.role.value if feature else self._infer_role(col, spec),
                "logical_type": feature.dtype.value if feature else "derived",
                "description": (feature.description if feature else "")
                or self._auto_description(col, spec),
                "missing_pct": round(float(df[col].isna().mean() * 100), 2),
                "n_unique": int(df[col].nunique(dropna=True)),
            }
            if feature and feature.categories:
                entry["categories"] = feature.categories
            rows.append(entry)
        return rows

    def dataset_card(self, result: GenerationResult) -> str:
        spec = result.spec
        df = result.data
        lines = [
            f"# Dataset Card: {spec.name}",
            "",
            f"- **Domain:** {spec.domain}",
            f"- **Task:** {spec.task_type.value}",
            f"- **Rows:** {len(df):,}",
            f"- **Columns:** {df.shape[1]}",
            f"- **Random seed:** {spec.random_seed}",
        ]
        if spec.target is not None:
            lines.append(f"- **Target:** `{spec.target.name}`")
        if result.evaluation is not None:
            lines.append(
                f"- **ML readiness score:** {result.evaluation.ml_readiness_score}/100"
            )
        lines += ["", "## Description", "", spec.description or "(none provided)", ""]

        if result.evaluation and result.evaluation.metrics:
            lines += ["## Baseline model", ""]
            lines.append(f"Model: `{result.evaluation.baseline_model}`")
            lines.append("")
            for k, v in result.evaluation.metrics.items():
                lines.append(f"- {k}: {v}")
            lines.append("")

        lines += ["## Columns", "", "| Column | Type | Role | Description |",
                  "| --- | --- | --- | --- |"]
        for entry in result.data_dictionary:
            lines.append(
                f"| {entry['column']} | {entry['logical_type']} | {entry['role']} | "
                f"{entry['description']} |"
            )
        lines += ["", "## Data quality injected", ""]
        q = spec.quality
        lines += [
            f"- Missing rate: {q.missing_rate}",
            f"- Duplicate rate: {q.duplicate_rate}",
            f"- Outlier rate: {q.outlier_rate}",
            f"- Noise: {q.noise}",
            "",
            "_Generated by the ML Dataset Generator Agent._",
        ]
        return "\n".join(lines)

    def json_schema(self, spec: DatasetSpec) -> dict[str, Any]:
        return spec.model_dump(mode="json")

    def _infer_role(self, col: str, spec: DatasetSpec) -> str:
        if spec.target and col == spec.target.name:
            return "target"
        if col in {"timestamp"}:
            return "time"
        return "feature"

    def _auto_description(self, col: str, spec: DatasetSpec) -> str:
        if spec.target and col == spec.target.name:
            return f"Target variable for {spec.task_type.value}"
        if col == "timestamp":
            return "Observation timestamp"
        return "Generated column"

    def run(self, result: GenerationResult) -> GenerationResult:
        result.data_dictionary = self.data_dictionary(result.data, result.spec)
        self.log("documentation generated")
        return result
