"""Shared schemas: the data-trust / provenance model and common enums.

Every externally-derived fact in the system is wrapped in a :class:`DataPoint`
so the UI (and the user) can always tell verified/live data apart from
estimates or AI recommendations. This is the backbone of section 19 of the
product spec ("Data Trust Model").
"""
from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Generic, TypeVar

from pydantic import BaseModel, Field

T = TypeVar("T")


class DataTrust(str, Enum):
    """How much a piece of information can be relied upon."""

    VERIFIED = "verified"          # confirmed against an authoritative source
    LIVE = "live"                  # fetched in real time from an external API
    RECENT = "recent"              # cached but fresh
    ESTIMATED = "estimated"        # heuristic / statistical estimate
    AI_RECOMMENDATION = "ai_recommendation"  # generated by the LLM
    USER_PROVIDED = "user_provided"


class Freshness(str, Enum):
    REAL_TIME = "real_time"
    HOURS = "hours"
    DAYS = "days"
    STATIC = "static"
    UNKNOWN = "unknown"


class DataPoint(BaseModel, Generic[T]):
    """A single value carrying its provenance.

    Never present a value to the user without its trust level. When the value
    comes from the LLM, ``trust`` must be ``AI_RECOMMENDATION`` — the system
    must never dress a hallucination up as a fact.
    """

    value: T
    source: str = "system"
    trust: DataTrust = DataTrust.AI_RECOMMENDATION
    freshness: Freshness = Freshness.UNKNOWN
    confidence: float = Field(0.5, ge=0.0, le=1.0)
    retrieved_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    note: str | None = None

    @classmethod
    def estimate(cls, value: T, source: str = "heuristic", confidence: float = 0.5) -> "DataPoint[T]":
        return cls(value=value, source=source, trust=DataTrust.ESTIMATED, confidence=confidence)

    @classmethod
    def ai(cls, value: T, source: str = "llm", confidence: float = 0.6) -> "DataPoint[T]":
        return cls(value=value, source=source, trust=DataTrust.AI_RECOMMENDATION, confidence=confidence)

    @classmethod
    def live(cls, value: T, source: str, freshness: Freshness = Freshness.REAL_TIME) -> "DataPoint[T]":
        return cls(value=value, source=source, trust=DataTrust.LIVE, freshness=freshness, confidence=0.95)


class Money(BaseModel):
    amount: float = Field(..., ge=0)
    currency: str = "USD"

    def __str__(self) -> str:  # pragma: no cover - convenience
        return f"{self.amount:,.0f} {self.currency}"


class GeoPoint(BaseModel):
    lat: float = Field(..., ge=-90, le=90)
    lng: float = Field(..., ge=-180, le=180)


class TravelStyle(str, Enum):
    BUDGET = "budget"
    COMFORT = "comfort"
    LUXURY = "luxury"


class TravelerType(str, Enum):
    SOLO = "solo"
    COUPLE = "couple"
    FAMILY = "family"
    BUSINESS = "business"
    GROUP = "group"


class Recommendation(str, Enum):
    MUST_SEE = "must_see"
    HIGHLY_RECOMMENDED = "highly_recommended"
    OPTIONAL = "optional"
    HIDDEN_GEM = "hidden_gem"
