"""Render a :class:`Brief` to a dated Markdown document and save it."""

from __future__ import annotations

import logging
from pathlib import Path

from .models import Brief

logger = logging.getLogger(__name__)


def render_markdown(brief: Brief) -> str:
    """Build the Markdown string for a brief."""
    date_str = brief.generated_at.strftime("%d %B %Y")
    time_str = brief.generated_at.strftime("%H:%M UTC")

    lines: list[str] = [
        f"# 🗞️ UPSC Daily Current Affairs — {date_str}",
        "",
        f"> Auto-generated by **cribasagent** at {time_str} from "
        f"{brief.source_count} Indian English news sources "
        f"({brief.article_count} articles scanned, last 24 hours).",
        "",
        "---",
        "",
    ]

    if not brief.sections:
        lines.append("_No exam-relevant current affairs found in the window._")
        return "\n".join(lines) + "\n"

    for subject, points in brief.sections.items():
        lines.append(f"## {subject}")
        lines.append("")
        for point in points:
            lines.append(f"- {point}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Revise daily. Consistency beats intensity. 📚*")
    return "\n".join(lines) + "\n"


def save_brief(brief: Brief, output_dir: Path) -> Path:
    """Write the brief to ``output_dir`` and return the file path."""
    output_dir.mkdir(parents=True, exist_ok=True)
    filename = f"upsc-current-affairs-{brief.generated_at.strftime('%Y-%m-%d')}.md"
    path = output_dir / filename
    path.write_text(render_markdown(brief), encoding="utf-8")
    logger.info("Saved brief to %s", path)
    return path
